config/routes.rb
Hausaufgabe23::Application.routes.draw do
  resources :rutes

  resources :graphs
  
  match '/pages/app' , :to => 'pages#app'
  match '/graphs' , :to => 'graphs#index'
  match '/rutes' , :to => 'rutes#index'
  match '/rute' , :to => 'pages#rute'
  root :to => 'pages#home'
end

app/models/graph.rb
class Graph < ActiveRecord::Base
end

app/models/rute.rb
class Rute < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  # GET /graphs
  # GET /graphs.xml
  def index
    @graphs = Graph.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @graphs }
    end
  end

  # GET /graphs/1
  # GET /graphs/1.xml
  def show
    @graph = Graph.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @graph }
    end
  end

  # GET /graphs/new
  # GET /graphs/new.xml
  def new
    @graph = Graph.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @graph }
    end
  end

  # GET /graphs/1/edit
  def edit
    @graph = Graph.find(params[:id])
    @title = "Edit"
  end

  # POST /graphs
  # POST /graphs.xml
  def create
    @graph = Graph.new(params[:graph])
    @title = "Create"

    respond_to do |format|
      if @graph.save
        format.html { redirect_to(@graph, :notice => 'Graph was successfully created.') }
        format.xml  { render :xml => @graph, :status => :created, :location => @graph }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @graph.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /graphs/1
  # PUT /graphs/1.xml
  def update
    @graph = Graph.find(params[:id])
    
    @title = "Update"

    respond_to do |format|
      if @graph.update_attributes(params[:graph])
        format.html { redirect_to(@graph, :notice => 'Graph was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @graph.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /graphs/1
  # DELETE /graphs/1.xml
  def destroy
  
  	@title = "Destroy"
    @graph = Graph.find(params[:id])
    @graph.destroy

    respond_to do |format|
      format.html { redirect_to(graphs_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	@title = "Startseite"
	
   @graphs = Graph.all
     @rutes = Rute.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @graphs }
    end
    
    
  end

  def rute
  	@info = " "
  end
  
end

app/controllers/rutes_controller.rb
class RutesController < ApplicationController
  # GET /rutes
  # GET /rutes.xml
  def index
    @rutes = Rute.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rutes }
    end
  end

  # GET /rutes/1
  # GET /rutes/1.xml
  def show
    @rute = Rute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rute }
    end
  end

  # GET /rutes/new
  # GET /rutes/new.xml
  def new
    @rute = Rute.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rute }
    end
    
  end

  # GET /rutes/1/edit
  def edit
    @rute = Rute.find(params[:id])
  end

  # POST /rutes
  # POST /rutes.xml
  def create
    @rute = Rute.new(params[:rute])

    respond_to do |format|
      if @rute.save
        format.html { redirect_to(@rute, :notice => 'Rute was successfully created.') }
        format.xml  { render :xml => @rute, :status => :created, :location => @rute }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rute.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rutes/1
  # PUT /rutes/1.xml
  def update
    @rute = Rute.find(params[:id])

    respond_to do |format|
      if @rute.update_attributes(params[:rute])
        format.html { redirect_to(@rute, :notice => 'Rute was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rute.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rutes/1
  # DELETE /rutes/1.xml
  def destroy
    @rute = Rute.find(params[:id])
    @rute.destroy

    respond_to do |format|
      format.html { redirect_to(rutes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def logo
		logo = image_tag("browsergame_test_banner.jpg", :alt => "Browsergame Test", :class => "round")   
	end

	def title
		base_title = "Hausaufgabe"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
	
	def f

  	rute = Rute.last.rute.split('-')
	graph = 0
	x = 0
	f= 0
	

	
	if (graph = Graph.where(:start => rute[x] , :end => rute[x+1] ).empty?)
		f = "Rute nicht berechenbar!"
		graph = 0
	else
	
	  while x < rute.length-1 do
		graph = Graph.where(:start => rute[x] , :end => rute[x+1] )
		f = f + graph.first.length
		x = x +1
      end 
    end
    
	f = f
			
  end
end

app/helpers/graphs_helper.rb
module GraphsHelper

end

app/helpers/rutes_helper.rb
module RutesHelper

  def f

  	rute = Rute.last.rute.split('-')
	graph = 0
	x = 0
	f= 0
	

	
	if (graph = Graph.where(:start => rute[x] , :end => rute[x+1] ).empty?)
		f = "Rute nicht berechenbar!"
		graph = 0
	else
	
	  while x < rute.length-1 do
		graph = Graph.where(:start => rute[x] , :end => rute[x+1] )
		f = f + graph.first.length
		x = x +1
      end 
    end
    
	f = f
			
  end
end

app/views/graphs/_form.html.erb
<%= form_for(@graph) do |f| %>
  <% if @graph.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@graph.errors.count, "error") %> prohibited this graph from being saved:</h2>

      <ul>
      <% @graph.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br />
    <%= f.text_field :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.text_field :end %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.text_field :length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/graphs/edit.html.erb
<h1>Editing graph</h1>

<%= render 'form' %>

<%= link_to 'Show', @graph %> |
<%= link_to 'Back', graphs_path %>

app/views/graphs/index.html.erb
<h1>Listing graphs</h1>

<table>
  <tr>
    <th>Start</th>
    <th>End</th>
    <th>Length</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @graphs.each do |graph| %>
  <tr>
    <td><%= graph.start %></td>
    <td><%= graph.end %></td>
    <td><%= graph.length %></td>
    <td><%= link_to 'Show', graph %></td>
    <td><%= link_to 'Edit', edit_graph_path(graph) %></td>
    <td><%= link_to 'Destroy', graph, :confirm => 'Are you sure?', :method => :delete %></td>
    
  </tr>
<% end %>
</table>

<%= link_to 'New Graph', new_graph_path %>

<br />
<br />

		
     


	

app/views/graphs/new.html.erb
<h1>New graph</h1>

<%= render 'form' %>

<%= link_to 'Back', graphs_path %>

app/views/graphs/rute.html.erb
<h1>New graph</h1>

<%= render 'form' %>

<%= link_to 'Back', graphs_path %>

app/views/graphs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start:</b>
  <%= @graph.start %>
</p>

<p>
  <b>End:</b>
  <%= @graph.end %>
</p>

<p>
  <b>Length:</b>
  <%= @graph.length %>
</p>


<%= link_to 'Edit', edit_graph_path(@graph) %> |
<%= link_to 'Back', graphs_path %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Startseite", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Startseite", root_path %></li>
	  <li><%= link_to "Graphs", graphs_path %></li>
	    <li><%= link_to "Rute", rutes_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <h2><%= debug(params) if Rails.env.development? %> </h2>

    </div>
  </body>
</html>

app/views/pages/app.html.erb
<h1>Hausaufgabe 2 und 3</h1>

<%= f %>

app/views/pages/home.html.erb
<h1>Hausaufgabe 2 und 3</h1>
Um einen neuen Grafen hinzuzufügen - auf Grafen klicken. <br />
Um eine Rute hinzuzufügen auf Rute klicken und eine neue hinzufügen - diese wird dann ausgerechnet.
<br /><br /><br />

<h1>Listing graphs</h1>

<table>
  <tr>
    <th>Start</th>
    <th>End</th>
    <th>Length</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @graphs.each do |graph| %>
  <tr>
    <td><%= graph.start %></td>
    <td><%= graph.end %></td>
    <td><%= graph.length %></td>
    <td><%= link_to 'Show', graph %></td>
    <td><%= link_to 'Edit', edit_graph_path(graph) %></td>
    <td><%= link_to 'Destroy', graph, :confirm => 'Are you sure?', :method => :delete %></td>
    
  </tr>
<% end %>
</table>
<%= link_to 'New Graph', new_graph_path %>


<h1>Listing rutes</h1>

<table>
  <tr>
    <th>Rute</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rutes.each do |rute| %>
  <tr>
    <td><%= rute.rute %></td>
    <td><%= link_to 'Show', rute %></td>
    <td><%= link_to 'Edit', edit_rute_path(rute) %></td>
    <td><%= link_to 'Destroy', rute, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Rute', new_rute_path %>




Strecke der LETZTEN Rute : <b> <%= f %> </b>

	

app/views/rutes/_form.html.erb
<%= form_for(@rute) do |f| %>
  <% if @rute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rute.errors.count, "error") %> prohibited this rute from being saved:</h2>

      <ul>
      <% @rute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rute %><br />
    <%= f.text_field :rute %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rutes/edit.html.erb
<h1>Editing rute</h1>

<%= render 'form' %>

<%= link_to 'Show', @rute %> |
<%= link_to 'Back', rutes_path %>

app/views/rutes/index.html.erb
<h1>Listing rutes</h1>

<table>
  <tr>
    <th>Rute</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rutes.each do |rute| %>
  <tr>
    <td><%= rute.rute %></td>
    <td><%= link_to 'Show', rute %></td>
    <td><%= link_to 'Edit', edit_rute_path(rute) %></td>
    <td><%= link_to 'Destroy', rute, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rute', new_rute_path %>
<br />
<br />
Strecke der LETZTEN Rute : <b> <%= f %> </b>

app/views/rutes/new.html.erb
<h1>New rute</h1>

<%= render 'form' %>

<%= link_to 'Back', rutes_path %>

app/views/rutes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rute:</b>
  <%= @rute.rute %>
</p>


<%= link_to 'Edit', edit_rute_path(@rute) %> |
<%= link_to 'Back', rutes_path %>